version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5435:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  redis:
    image: redis

  api:
    build:
        context: ./server
        dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis://redis:6379
      - PORT=4000

  client: 
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_SERVER_URL=http://localhost:4000/ 
    ports:
      - 80:80


volumes:
  db:
    driver: local